import type { Db } from "../db/client";
import {
  agendaHu,
  agendaWeekly,
  areas,
  avanceAreaBase,
  calendario,
  configuracion,
  festivos,
  historias,
  lineas,
  milestoneDependencia,
  milestoneHistoria,
  milestoneRiesgo,
  milestones,
  milestoneTarea,
  notas,
  riesgos,
  sprints,
  tareaPredecesora,
  tareas,
} from "../db/schema";
import type { Raw } from "./model";

/** Lee todas las tablas que alimentan el modelo (consultas en paralelo; el volumen es pequeño). */
export async function loadRaw(db: Db): Promise<Raw> {
  const [
    lineasR,
    areasR,
    sprintsR,
    festivosR,
    calendarioR,
    milestonesR,
    historiasR,
    tareasR,
    predR,
    msHuR,
    msTareaR,
    msDepR,
    msRiesgoR,
    riesgosR,
    notasR,
    weeklyR,
    agendaHuR,
    baseR,
    configR,
  ] = await Promise.all([
    db.select().from(lineas),
    db.select().from(areas),
    db.select().from(sprints),
    db.select().from(festivos),
    db.select().from(calendario),
    db.select().from(milestones),
    db.select().from(historias),
    db.select().from(tareas),
    db.select().from(tareaPredecesora),
    db.select().from(milestoneHistoria),
    db.select().from(milestoneTarea),
    db.select().from(milestoneDependencia),
    db.select().from(milestoneRiesgo),
    db.select().from(riesgos),
    db.select().from(notas),
    db.select().from(agendaWeekly),
    db.select().from(agendaHu),
    db.select().from(avanceAreaBase),
    db.select().from(configuracion),
  ]);
  return {
    lineas: lineasR,
    areas: areasR,
    sprints: sprintsR,
    festivos: festivosR,
    calendario: calendarioR,
    milestones: milestonesR,
    historias: historiasR,
    tareas: tareasR,
    predecesoras: predR,
    msHu: msHuR,
    msTarea: msTareaR,
    msDep: msDepR,
    msRiesgo: msRiesgoR,
    riesgos: riesgosR,
    notas: notasR,
    agendaWeekly: weeklyR,
    agendaHu: agendaHuR,
    base: baseR,
    config: Object.fromEntries(configR.map((c) => [c.clave, c.valor])),
  };
}